services:
  # db:
  #   image: postgres:17.2-alpine3.21
  #   container_name: postgres_container
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root123
  #     POSTGRES_DB: mobiledev
  #   volumes:
  #     - ./data:/var/lib/postgresql/mobiledev/data
  #   ports:
  #     - 5432:5432
  redis:
    image: redis:7.4.2-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=quangamingvn123
    volumes:
      - ./data:/var/lib/redis/mobiledev/data
    command: ["redis-server", "--requirepass", "quangamingvn123"]

volumes:
  # db:
  #   driver: local
  redis:
    driver: local
