pipeline{
    agent any

    environment {
        remote = [
            name: 'backend-vm',
            host: 'meomeo-backend.southeastasia.cloudapp.azure.com',
            user: 'backend-vm',
            identity: credentials('backend-vm-ssh-key'),
            allowAnyHosts: true
        ]
    }
    stages{
        stage('SSH'){
            steps{
                sshCommand remote: remote, command: 'cd /app/backend && git pull && npm install'
                sshCommand remote: remote, command: 'systemctl restart nest-backend.service'
            }
        }
    }
}