pipeline{
    agents any

    stages{

        def remote = [:]
        remote.name = 'backend-vm'
        remote.host = 'meomeo-backend.southeastasia.cloudapp.azure.com'
        remote.user = 'backend-vm'
        remote.identity = credentials('backend-vm-ssh-key')
        remote.allowAnyHosts = true

        stage('SSH'){
            steps{
                sshcommand remote: remote, command: 'cd /app/backend && git pull && npm install'
                sshcommand remote: remote, command: 'systemctl restart nest-backend.service'
            }
        }
    }
}