pipeline{
    agent any

    stages{
        script {
            def remote = [:]
            remote.name = 'backend-vm'
            remote.host = 'meomeo-backend.southeastasia.cloudapp.azure.com'
            remote.user = 'backend-vm'
            remote.identity = credentials('backend-vm-ssh-key')
            remote.allowAnyHosts = true
        }

        stage('SSH'){
            steps{
                sshCommand remote: remote, command: 'cd /app/backend && git pull && npm install'
                sshCommand remote: remote, command: 'systemctl restart nest-backend.service'
            }
        }
    }
}